version: 2

references:
  container_config: &container_config
    docker:
      # Main Python container
      - image: circleci/python:3.7.7

jobs:
  build:
    <<: *container_config

    steps:
      - checkout
      - run:
          name: 'Setup virtual environment'
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -e .[test]

      - run:
          name: 'Pylinting'
          command: |
            . venv/bin/activate
            pylint target_bigquery -d C,W,unexpected-keyword-arg,duplicate-code

      - run:
          name: 'Unit Tests'
          command: |
            . venv/bin/activate
            export LOGGING_CONF_FILE=$(pwd)/sample_logging.conf
            nosetests --where=tests/unit

      # Integration test currently turned off
      #- run:
      #    name: 'Integration Tests'
      #    command: |
      #      . venv/bin/activate
      #      export LOGGING_CONF_FILE=$(pwd)/sample_logging.conf
      #      nosetests --where=tests/integration/

workflows:
  version: 2
  build:
    jobs:
      - build
